name: Spark_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@master
        with:
          go-version: '>=1.21.0'

      - name: Download application dependencies
        run: go mod download

      - name: Building application
        run: go build .
